services:
  - type: worker
    name: miss-cherry-bot
    runtime: python
    plan: starter
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER_ID
        sync: false
      - key: LOG_GROUP_ID
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_NAME
        value: MissCherryDB
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: DEEPSEEK_MODEL
        value: deepseek-chat
      - key: BOT_NAME
        value: Miss Cherry 🍒
      - key: START_IMG
        sync: false
      - key: SUPPORT_LINK
        sync: false
      - key: UPDATE_LINK
        sync: false
      - key: SOURCE_LINK
        sync: false
      - key: DOCS_URL
        sync: false
      - key: OWNER_USERNAME
        sync: false
      - key: DEVELOPER_USERNAME
        sync: false
